// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wegzylnyopbcnutmtigk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndlZ3p5bG55b3BiY251dG10aWdrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQwMDY0NzEsImV4cCI6MjA1OTU4MjQ3MX0.bK0B0dqpDDMgfeV8Co4q7ydBmwjPuwUzl2fnvgA5Pm0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);